name: 'Build and release'

on:
  push:
    branches:
      - dev
      - main
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TARGETS: f7
  DEFAULT_TARGET: f7
  FBT_GIT_SUBMODULE_SHALLOW: 1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Read version tag"
        run: bash .github/workflow_data/commit.sh

      - name: 'Build the firmware'
        run: |
          set -e
          for TARGET in ${TARGETS}; do
            TARGET_HW="$(echo "${TARGET}" | sed 's/f//')"; \
            ./fbt TARGET_HW=$TARGET_HW DIST_SUFFIX=$VERSION_TAG updater_package
          done

      - name: "Check for uncommitted changes"
        run: |
          git diff --exit-code

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist/${{ env.DEFAULT_TARGET }}-*/
          
      - name: "Make tgz, zip and sdk"
        run: bash .github/workflow_data/package.sh

      - name: "Update release notes"
        run: python .github/workflow_data/release.py

      - name: "Make release"
        uses: softprops/action-gh-release@v1
        with:
          body_path: ".github/workflow_data/release.md"
          draft: false
          prerelease: false
          files: |
            ${{ env.ARTIFACT_TGZ }}
            ${{ env.ARTIFACT_ZIP }}
            ${{ env.ARTIFACT_SDK }}
          name: "${{ env.VERSION_TAG }}"
          tag_name: "${{ env.VERSION_TAG }}"
          target_commitish: ${{ github.event.pull_request.base.ref }}

