name: 'Build PR'

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TARGETS: f7
  DEFAULT_TARGET: f7

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "Read version tag"
        run: bash .github/workflow_data/commit.sh

      - name: 'Build the firmware'
        run: |
          set -e
          for TARGET in ${TARGETS}; do
            TARGET_HW="$(echo "${TARGET}" | sed 's/f//')"; \
            ./fbt TARGET_HW=$TARGET_HW DIST_SUFFIX=$VERSION_TAG updater_package
          done

      - name: "Check for uncommitted changes"
        run: |
          git diff --exit-code

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: tgz_package
          path: |
            ${{ env.ARTIFACT_TGZ }}
          
      - name: "Make tgz, zip and sdk"
        run: bash .github/workflow_data/package.sh
